<a href="https://colab.research.google.com/github/jrhumberto/2026-mestrado-pep/blob/main/unir_bases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Etapa Inicial: Instalação de Pacotes

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


governadores = pd.read_csv('https://raw.githubusercontent.com/jrhumberto/000-pep/refs/heads/main/data/eleicoes_uf_2018_2022_austeridade.csv')
endividamento = pd.read_csv('https://raw.githubusercontent.com/jrhumberto/000-pep/refs/heads/main/data/endividamento_estados_2018_2024.csv')


endividamento['austeridade'] = 0

In [45]:
endividamento.head(50)

    uf   ano     dcl_valor  pessoal_pct_rcl  austeridade
0   AC  2018  3.565447e+09            48.01            0
1   AC  2019  3.116892e+09            53.74            0
2   AC  2020  3.337030e+09            52.69            0
3   AC  2021  2.847799e+09            51.44            0
4   AC  2022  2.505322e+09            46.36            0
5   AC  2023  2.051524e+09            48.41            0
6   AC  2024  1.978575e+09            46.77            0
7   AL  2018  6.816346e+09            48.69            0
8   AL  2019  6.404122e+09            44.71            0
9   AL  2020  5.813490e+09            39.78            0
10  AL  2021  4.758264e+09            35.60            0
11  AL  2022  7.245315e+09            40.90            0
12  AL  2023  1.013631e+10            43.01            0
13  AL  2024  1.282632e+10            36.08            0
14  AM  2018  4.592049e+09            48.33            0
15  AM  2019  4.389403e+09            49.65            0
16  AM  2020  2.824602e+09            48.35            0
17  AM  2021  4.214587e+09            46.70            0
18  AM  2022  5.234362e+09            41.10            0
19  AM  2023  5.899489e+09            40.17            0
20  AM  2024  7.870288e+09            38.77            0
21  AP  2018  6.071966e+07            40.07            0
22  AP  2019  1.933086e+09            39.25            0
23  AP  2020  2.501413e+09            45.46            0
24  AP  2021 -1.381052e+09            42.32            0
25  AP  2022  2.272124e+09            40.95            0
26  AP  2023  8.312293e+08            41.72            0
27  AP  2024 -6.091381e+08            43.51            0
28  BA  2018  2.049358e+10            46.13            0
29  BA  2019  2.152671e+10            43.85            0
30  BA  2020  2.151187e+10            40.95            0
31  BA  2021  1.727979e+10            35.57            0
32  BA  2022  1.665426e+10            36.20            0
33  BA  2023  2.084110e+10            39.98            0
34  BA  2024  2.408325e+10            41.65            0
35  CE  2018  1.096243e+10            42.30            0
36  CE  2019  1.099517e+10            41.64            0
37  CE  2020  1.197362e+10            40.55            0
38  CE  2021  1.110832e+10            39.01            0
39  CE  2022  1.021726e+10            42.83            0
40  CE  2023  9.501907e+09            44.73            0
41  CE  2024  1.200271e+10            43.54            0
42  DF  2018  7.647511e+09            43.46            0
43  DF  2019  8.116311e+09            43.54            0
44  DF  2020  8.193095e+09            42.05            0
45  DF  2021  5.804218e+09            39.52            0
46  DF  2022  7.754225e+09            44.17            0
47  DF  2023  7.629947e+09            34.80            0
48  DF  2024  4.714681e+09            39.57            0
49  ES  2018  2.571462e+09            41.69            0

In [46]:
import numpy as np
list_year = list(endividamento.ano.unique())
list_uf = list(endividamento.uf.unique())


for x in list_uf:
  for y in list_year:
    pleito = 2018 if y <=2022 else 2022 # Se o exercicio for 2019, 2020, 2021 e 2022 pegará a austeridade do candidato eleito em 2018;
    f1 = governadores['ANO_ELEICAO'] == z
    f2 = governadores['SG_UF'] == x
    austeridade = int(governadores[ f1 & f2]['austeridade'].iloc[0])
    endividamento.loc[ (endividamento['uf'] == x) & (endividamento['ano'] == y), 'austeridade'] = austeridade


endividamento.head(50)

    uf   ano     dcl_valor  pessoal_pct_rcl  austeridade
0   AC  2018  3.565447e+09            48.01            0
1   AC  2019  3.116892e+09            53.74            0
2   AC  2020  3.337030e+09            52.69            0
3   AC  2021  2.847799e+09            51.44            0
4   AC  2022  2.505322e+09            46.36            0
5   AC  2023  2.051524e+09            48.41            0
6   AC  2024  1.978575e+09            46.77            0
7   AL  2018  6.816346e+09            48.69            0
8   AL  2019  6.404122e+09            44.71            0
9   AL  2020  5.813490e+09            39.78            0
10  AL  2021  4.758264e+09            35.60            0
11  AL  2022  7.245315e+09            40.90            0
12  AL  2023  1.013631e+10            43.01            0
13  AL  2024  1.282632e+10            36.08            0
14  AM  2018  4.592049e+09            48.33            1
15  AM  2019  4.389403e+09            49.65            1
16  AM  2020  2.824602e+09            48.35            1
17  AM  2021  4.214587e+09            46.70            1
18  AM  2022  5.234362e+09            41.10            1
19  AM  2023  5.899489e+09            40.17            1
20  AM  2024  7.870288e+09            38.77            1
21  AP  2018  6.071966e+07            40.07            0
22  AP  2019  1.933086e+09            39.25            0
23  AP  2020  2.501413e+09            45.46            0
24  AP  2021 -1.381052e+09            42.32            0
25  AP  2022  2.272124e+09            40.95            0
26  AP  2023  8.312293e+08            41.72            0
27  AP  2024 -6.091381e+08            43.51            0
28  BA  2018  2.049358e+10            46.13            0
29  BA  2019  2.152671e+10            43.85            0
30  BA  2020  2.151187e+10            40.95            0
31  BA  2021  1.727979e+10            35.57            0
32  BA  2022  1.665426e+10            36.20            0
33  BA  2023  2.084110e+10            39.98            0
34  BA  2024  2.408325e+10            41.65            0
35  CE  2018  1.096243e+10            42.30            0
36  CE  2019  1.099517e+10            41.64            0
37  CE  2020  1.197362e+10            40.55            0
38  CE  2021  1.110832e+10            39.01            0
39  CE  2022  1.021726e+10            42.83            0
40  CE  2023  9.501907e+09            44.73            0
41  CE  2024  1.200271e+10            43.54            0
42  DF  2018  7.647511e+09            43.46            0
43  DF  2019  8.116311e+09            43.54            0
44  DF  2020  8.193095e+09            42.05            0
45  DF  2021  5.804218e+09            39.52            0
46  DF  2022  7.754225e+09            44.17            0
47  DF  2023  7.629947e+09            34.80            0
48  DF  2024  4.714681e+09            39.57            0
49  ES  2018  2.571462e+09            41.69            0

In [47]:
from scipy import stats

df = endividamento.copy()

# Separar grupos
s0 = df.loc[df['austeridade'] == 0, 'dcl_valor']
s1 = df.loc[df['austeridade'] == 1, 'dcl_valor']
# Teste t com variâncias desiguais (Welch)
t_stat, p_val = stats.ttest_ind(
s1, s0,
equal_var=False,
nan_policy='omit'
)
print(f"Teste t (Welch) dcl_valor - austeridade vs outros")
print(f"t = {t_stat:.3f}, p-valor = {p_val:.4f}")
print(f"Média grupo 0 (não austeridade): {s0.mean():.2f}")
print(f"Média grupo 1 (austeridade): {s1.mean():.2f}")

Teste t (Welch) dcl_valor - austeridade vs outros
t = 5.729, p-valor = 0.0000
Média grupo 0 (não austeridade): 5332081714.27
Média grupo 1 (austeridade): 53697496310.98

In [50]:
import statsmodels.formula.api as smf
# Criar dummies de UF e ano (efeitos fixos)
uf_d = pd.get_dummies(df['uf'], prefix='uf', drop_first=True)
ano_d = pd.get_dummies(df['ano'], prefix='ano', drop_first=True)
model_df = pd.concat([df, uf_d, ano_d], axis=1)

fe_uf = ' + '.join(uf_d.columns)
fe_ano = ' + '.join(ano_d.columns)

formula = (
'austeridade ~ dcl_valor +  pessoal_pct_rcl +' + fe_uf + ' + ' + fe_ano
)
model = smf.ols(formula=formula, data=model_df).fit(cov_type='HC3') # erros robustos
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            austeridade   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.357e+13
Date:                Tue, 24 Feb 2026   Prob (F-statistic):               0.00
Time:                        07:42:25   Log-Likelihood:                 2025.5
No. Observations:                 189   AIC:                            -3981.
Df Residuals:                     154   BIC:                            -3868.
Df Model:                          34
Covariance Type:                  HC3
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept         6.661e-16    1.1e-05   6.08e-11      1.000   -2.15e-05    2.15e-05
uf_AL[T.True]    -3.565e-14      2e-06  -1.78e-08      1.000   -3.93e-06    3.93e-06
uf_AM[T.True]        1.0000    1.1e-06   9.06e+05      0.000       1.000       1.000
uf_AP[T.True]      8.24e-16   1.59e-06   5.17e-10      1.000   -3.12e-06    3.12e-06
uf_BA[T.True]    -1.769e-15   4.37e-06  -4.05e-10      1.000   -8.57e-06    8.57e-06
uf_CE[T.True]      4.85e-15   2.39e-06   2.03e-09      1.000   -4.68e-06    4.68e-06
uf_DF[T.True]     1.077e-14   1.97e-06   5.47e-09      1.000   -3.86e-06    3.86e-06
uf_ES[T.True]      9.42e-16   2.44e-06   3.86e-10      1.000   -4.78e-06    4.78e-06
uf_GO[T.True]        1.0000   3.09e-06   3.23e+05      0.000       1.000       1.000
uf_MA[T.True]    -3.705e-15   2.48e-06  -1.49e-09      1.000   -4.86e-06    4.86e-06
uf_MG[T.True]        1.0000   3.04e-05   3.29e+04      0.000       1.000       1.000
uf_MS[T.True]        1.0000   1.31e-06   7.65e+05      0.000       1.000       1.000
uf_MT[T.True]        1.0000   1.57e-06   6.35e+05      0.000       1.000       1.000
uf_PA[T.True]     6.838e-15   1.61e-06   4.24e-09      1.000   -3.16e-06    3.16e-06
uf_PB[T.True]     4.651e-15   5.33e-07   8.72e-09      1.000   -1.04e-06    1.04e-06
uf_PE[T.True]        1.0000   2.53e-06   3.95e+05      0.000       1.000       1.000
uf_PI[T.True]    -5.105e-15   1.56e-06  -3.27e-09      1.000   -3.06e-06    3.06e-06
uf_PR[T.True]        1.0000   1.74e-06   5.74e+05      0.000       1.000       1.000
uf_RJ[T.True]        1.0000   3.74e-05   2.67e+04      0.000       1.000       1.000
uf_RN[T.True]     8.667e-15   1.58e-06    5.5e-09      1.000   -3.09e-06    3.09e-06
uf_RO[T.True]        1.0000   2.19e-06   4.57e+05      0.000       1.000       1.000
uf_RR[T.True]     7.724e-15   1.08e-06   7.14e-09      1.000   -2.12e-06    2.12e-06
uf_RS[T.True]        1.0000   2.14e-05   4.66e+04      0.000       1.000       1.000
uf_SC[T.True]        1.0000   3.46e-06   2.89e+05      0.000       1.000       1.000
uf_SE[T.True]        1.0000   9.35e-07   1.07e+06      0.000       1.000       1.000
uf_SP[T.True]        1.0000   6.06e-05   1.65e+04      0.000       1.000       1.000
uf_TO[T.True]        1.0000   7.62e-07   1.31e+06      0.000       1.000       1.000
ano_2019[T.True] -1.148e-15   1.81e-06  -6.33e-10      1.000   -3.55e-06    3.55e-06
ano_2020[T.True]  2.709e-15   2.14e-06   1.27e-09      1.000   -4.19e-06    4.19e-06
ano_2021[T.True]  1.117e-15   2.31e-06   4.83e-10      1.000   -4.54e-06    4.54e-06
ano_2022[T.True] -3.188e-15   2.29e-06  -1.39e-09      1.000   -4.48e-06    4.48e-06
ano_2023[T.True]  -1.78e-15   2.18e-06  -8.16e-10      1.000   -4.27e-06    4.27e-06
ano_2024[T.True] -1.665e-15    2.2e-06  -7.58e-10      1.000   -4.31e-06    4.31e-06
dcl_valor        -7.517e-17   2.24e-16     -0.335      0.738   -5.15e-16    3.64e-16
pessoal_pct_rcl  -1.897e-16   1.97e-07  -9.64e-10      1.000   -3.86e-07    3.86e-07
==============================================================================
Omnibus:                      122.318   Durbin-Watson:                   0.308
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              577.325
Skew:                           2.698   Prob(JB):                    4.32e-126
Kurtosis:                       9.647   Cond. No.                     4.07e+12
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 4.07e+12. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 34, but rank is 33
  warnings.warn('covariance of constraints does not have full '